language: java

before_script: cd "Power Up Proto"

install: ant

addons:
  sonarcloud:
    organization: "smaboticsmaster-github" # the key of the org you chose at step #3
    token:
      secure: "APgBOssFv3wdNjQXaBV1eU2B78KsoZ00grCsbyX/eWkRnW44n4cA2yoDeCGK8cTqCAjOnrUnm+wymRwE2l0asoPBbjdL9FV5weGBfICLySQHVjjMPrYQPv26swW+oyD+nDZ6Hpnbfo5FXnMcodRxINZ6ezT222/vB2KQSRo+Lm2NDcOnhgIvhgoZrUPtcxH51xE/dwP/4MJfpIrlyo88yv4LXnOD2vQQ+bi2kea+yDrcbKQGT6Bph5yLtybJ7SAsGDVMxY0O0puR0srvKLy//ge/aJZ8eTzY2yKL/FdH9Iq0uj1wx9Ae2Ch1WFazbBTAwsLQNjxXWU45kMel0UdP0DPxLIkihJPOFFg9MZfZM7fk3BOXVT35Ktz8OBzXTDvROIw27hlPNUAwnEz2E/YmJHu6OmeP7U2cnoVNOjvdT5cgFS21zhsqQtBGD/3FjPZbhd0fE53KwxVNQNyTWrkblqGn4w6DlAiHwFLhGNjqbnDb1vYbNtc6qiTA2KS8cmWsQLSbYFrmcwQUcBkNtkvBTTsI8qiAeHsST/tcJfSZDctLXq5b6Gz7kpM3odRJtLsELf7hzWiXO9POf5rMYIxXlExsFhcBl3wW1okTXC62ov9sOz5mrj5HguyySFeRNNX6QntfWwBDVa/jIBV/wAQBo1VAs0cvFv6Hsp2sxuV19Oc="
    branches:
      - *
    github_token:
      secure: "gIpTD7xUXX9NydleB87VJp2z4lhLqKJfDzgYGeXj+D4pSaWHoZCB+odzq3wXQfxf2KVILTD1n48O2a8sHGBt4V4JnCF4qltapINOb7zDYzoklS1/VOZzPbhPw7BfsWRmGpJHVA1G2mz0wFF4iqVff8f92W2NXxdPmNkccbwDZc8iKJdtjeCcJuygtb1IwEZ/UhIkBcxpXeEHa/mP3CSaXQcxHckg3nvvALMWKLFt0AELNGrAPmpS/hGpr+WDYlR6xl6xJnvenEuDdn+XzUXN+Zcz6ncm07Nskp5rFBy8KxSMdqeojS8VzhqqaP6EClxjm+vTFJlHX8VMsGCl/JoALZm2H2D4huA/ycQ+K2tYeyVw/Ht1qg8F9veSwiyO0GJqxhrb/qalT89jwGOTXP3b+qagcspyIHK1CG7/OmnDv0A03C1gyz4ItsRVs+yQ1Ws4ATXhBBS5mmHGMuAFnI/O0bsoPjjSapwhIv53GAvFXVAqUyF+HMWuOnzTcngq2/UzJAapIsRSC4vrmCUQvrNFeoFf8QCf/u9We6wFYWl0GOFZnqrmF57Cd3dyNC4qHGL0OOhcieZhA7ltZiH2JHU9rBiVSBCOnWRh2aYQx9V2pxCBLJlLzUs7RCIaaKubUGV4R9L2PQR+Kq/ynncgazH9pWYlyB3UzXEPZ/nLReXX7M4="
script:
  - ant -f travis.build.xml
  # other script steps might be done before running the actual analysis
  - sonar-scanner -X

